[project]
name = "ppth-metrics"
version = "0.3.1"
description = "Prometheus exporter for system metrics and Tautulli/Plex streaming metrics"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "psutil==5.9.8",
    "requests==2.31.0",
]
